# Generated by Django 5.0.6 on 2024-07-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safecid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='eupmyundong',
            new_name='eupmyeondong',
        ),
    ]
