# Generated by Django 5.0.6 on 2024-08-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecid', '0002_rename_eupmyundong_address_eupmyeondong'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
